name: Build

on:
    push:
        branches:
            - main
        paths-ignore:
            - "README.md"
            - "CHANGELOG.md"
            - ".gitignore"
        tags-ignore:
            # This will ignore release versions tagged with a version identifier. We'll
            # use a separate workflow for them.
            - "v*"
    pull_request:
        paths-ignore:
            - README.md
            - "CHANGELOG.md"
            - ".gitignore"

jobs:
    build:
        name: Build
        runs-on: windows-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Dotnet
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 6.0.x

            - name: Build Mod for 1.5
              env:
                  RimWorldVersion: 1.5
              run: dotnet build .vscode --configuration Release

            - name: Upload Mod Artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: RealisticOrbitalTrade-${{ github.sha }}
                  path: |
                      About/
                      1.5/
                      Common/
                      Defs/
                      Patches/
                      LICENSE
                      LICENSE.Apache-2.0
                      LICENSE.MIT
                      README.md
                      CHANGELOG.md
                      !**/.*
                      !About/*.pdn
                      !About/*.svg
                      !About/*.ttf
