name: Build

on:
    workflow_call:
        inputs:
            artifact-suffix:
                required: true
                type: string

jobs:
    build:
        name: Build
        runs-on: windows-latest
        env:
            RimWorldSteamWorkshopFolderPath: ..\.deps\refs
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Dotnet
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 6.0.x

            - name: Build Mod for 1.5
              env:
                  RimWorldVersion: 1.5
              run: |
                  dotnet build --configuration Release .vscode/mod.csproj
                  dotnet build --configuration Release .vscode/wehadatrader.interop.csproj
                  dotnet build --configuration Release .vscode/tweaksgalore.interop.csproj

            - name: Build Mod for 1.4
              env:
                  RimWorldVersion: 1.4
              run: |
                  dotnet build .vscode --configuration Release
                  dotnet build --configuration Release .vscode/wehadatrader.interop.csproj

            - name: Upload Mod Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: RealisticOrbitalTrade-${{ inputs.artifact-suffix }}
                  path: |
                      About/
                      1.5/
                      1.4/
                      1.5_WeHadATrader/
                      1.4_WeHadATrader/
                      1.5_TweaksGalore/
                      Common/
                      UpdateLog/
                      Defs/
                      Patches/
                      LICENSE
                      LICENSE.Apache-2.0
                      LICENSE.MIT
                      README.md
                      CHANGELOG.md
                      LoadFolders.xml
                      !**/.*
                      !About/*.pdn
                      !About/*.svg
                      !About/*.ttf
